Remove homebrew bump action
Apparently:

"
Error: Whoops, the lazydocker formula has its version update
pull requests automatically opened by BrewTestBot!
We'd still love your contributions, though, so try another one
that's not in the autobump list
"

So looks like we don't need to have this action anymore because homebrew
will be updated automatically.